[package]
name = "chronoclean"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
color-eyre = "0.6.5"
dunce = "1.0.5"
humantime = "2.3.0"
trash = "5.2.5"
walkdir = "2.5"

[target.'cfg(windows)'.build-dependencies]
chrono = { version = "0.4.45", features = ["now"], default-features = false }
winresource = "0.1.31"

[profile.release]
opt-level = 3
lto = true
debug = "line-tables-only"